# Generated by Django 3.1.3 on 2021-07-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwash', '0002_booking_washplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='timeframe',
            field=models.IntegerField(choices=[('Morning', 'Morning'), ('Evening', 'evening'), ('Afternoon', 'afternoon')], default=0),
        ),
        migrations.AlterField(
            model_name='washplan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
