# Generated by Django 3.1.3 on 2021-07-27 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwash', '0005_auto_20210727_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='timeframe',
            field=models.CharField(choices=[('Morning', 'Morning'), ('Evening', 'Evening'), ('Afternoon', 'Afternoon')], default=0, max_length=50),
        ),
    ]
