# Generated by Django 3.1.3 on 2021-07-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cwash', '0008_auto_20210727_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='washplan',
            name='airfreshner',
        ),
        migrations.RemoveField(
            model_name='washplan',
            name='coat',
        ),
        migrations.RemoveField(
            model_name='washplan',
            name='dashboard',
        ),
        migrations.RemoveField(
            model_name='washplan',
            name='hdry',
        ),
        migrations.RemoveField(
            model_name='washplan',
            name='hwash',
        ),
        migrations.RemoveField(
            model_name='washplan',
            name='rainx',
        ),
        migrations.RemoveField(
            model_name='washplan',
            name='sealer',
        ),
        migrations.RemoveField(
            model_name='washplan',
            name='tdress',
        ),
        migrations.RemoveField(
            model_name='washplan',
            name='vacuum',
        ),
        migrations.RemoveField(
            model_name='washplan',
            name='vinyl',
        ),
        migrations.RemoveField(
            model_name='washplan',
            name='window',
        ),
        migrations.RemoveField(
            model_name='washplan',
            name='wshine',
        ),
    ]
