# Generated by Django 3.1.3 on 2021-07-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cwash', '0010_auto_20210728_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
