# Generated by Django 3.1.3 on 2021-07-28 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cwash', '0012_auto_20210728_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
