# Generated by Django 3.1.3 on 2021-07-28 20:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cwash', '0015_auto_20210728_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
